# Generated by Django 2.2.1 on 2019-06-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
