# Generated by Django 2.2.1 on 2019-06-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190619_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
