# Generated by Django 2.2.1 on 2019-06-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190619_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaluser',
            name='professional_license',
            field=models.ImageField(upload_to='license_files'),
        ),
    ]
