# Generated by Django 2.2.1 on 2019-06-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190621_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaluser',
            name='area_of_expertise',
            field=models.CharField(choices=[('doctor', 'doctor'), ('lawyer', 'lawyer'), ('therapist', 'therapist'), ('personal_trainer', 'personal_trainer'), ('home_tuition', 'home_tuition'), ('programmer', 'programmer')], default='doctor', max_length=20),
        ),
    ]
