# Generated by Django 2.2.2 on 2019-07-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190621_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
