# Generated by Django 2.2.1 on 2019-07-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_baseuser_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='address',
            new_name='hospital_address',
        ),
    ]
