# Generated by Django 2.2.1 on 2019-07-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190702_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaluser',
            name='area_of_expertise',
            field=models.CharField(choices=[('doctor', 'doctor'), ('lawyer', 'lawyer'), ('therapist', 'therapist'), ('personal_trainer', 'personal_trainer'), ('home_tuition', 'home_tuition'), ('programmer', 'programmer')], max_length=20),
        ),
    ]
